version: '3.7'
services:
  db:
    image: postgres:15-alpine
    env_file:
      - ./pkg/common/envs/.env
    environment:
        - POSTGRES_DB=my_warehouse_db
        - POSTGRES_USER=aslan
        - POSTGRES_PASSWORD=povt203
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "9080:5432"
    networks:
      - my-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GIN_MODE: release
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8090:8090"
    networks:
      - my-network

volumes:
  pgdata:
networks:
  my-network:
